// This file is part of the research.fi API service
//
// Copyright 2019 Ministry of Education and Culture, Finland
//
// :author: CSC - IT Center for Science Ltd., Espoo Finland servicedesk@csc.fi
// :license: MIT
pipeline {
  agent {
    node {
      label 'nodejs' 
    }
  }
  options {
    timeout(time: 5, unit: 'MINUTES') 
  }
  stages {
    stage('Miscellaneous') {
      steps('Print environment variables') {
        echo "Running build ${env.BUILD_ID} on ${env.JENKINS_URL}"
        echo "Git commit is ${env.GIT_COMMIT}"
      }
    }
    stage('Build') {
      steps {
        script {
          openshift.withCluster() {
            openshift.withProject() {
              def buildConfig = openshift.selector("bc", "researchfi-api-build")
              buildConfig.startBuild().logs("-f")
            }
          }
        }
      }
    }
    //stage('Deploy') {
    //  steps {
    //    script {
    //      openshift.withCluster() {
    //        openshift.withProject() {
    //          def deploymentConfig = openshift.selector("dc", "researchfi-api-deployment")
    //          deploymentConfig.rollout()
    //        }
    //      }
    //    }
    //  }
    //}
    stage('Deploy to production') {
      steps {
        timeout(time: 1, unit: 'MINUTES') {
          input message: "Deploy to production?", ok: "Deploy"
        }
        script {
          openshift.withCluster() {
            openshift.withProject() {
              openshift.tag("researchfi-api-test-image:latest", "researchfi-api-prod-image:latest")
            }
          }
        }
      }
    }
  }
}