# This file is part of the research.fi API service
#
# Copyright 2019 Ministry of Education and Culture, Finland
#
# :author: CSC - IT Center for Science Ltd., Espoo Finland servicedesk@csc.fi
# :license: MIT
apiVersion: v1
kind: Template
metadata:
  labels:
    app: researchfi-api
    template: researchfi-api
  name: researchfi-api
objects:

# Service
- apiVersion: v1
  kind: Service
  metadata:
    name: researchfi-api-service
    annotations:
      description: Research.fi api service
  spec:
    ports:
      - name: api
        port: 8080
        targetPort: 8080
    selector:
      name: researchfi-api

# ImageStream
#- apiVersion: v1
#  kind: ImageStream
#  metadata:
#    name: researchfi-api

- apiVersion: v1
  kind: ImageStream
  metadata:
    name: researchfi-api-test-image

#- apiVersion: v1
#  kind: ImageStream
#  metadata:
#    name: researchfi-api-imagestream
#  spec:
#    dockerImageRepository: ${ARTIFACTORY}/researchfi-api-rahti/test
#    tags:
#    - from:
#        kind: DockerImage
#        name: ${ARTIFACTORY}/researchfi-api-rahti/test
#      name: latest
#      importPolicy:
#        insecure: false
#        scheduled: false
#      referencePolicy:
#        type: Source

# BuildConfig using source to image (s2i) strategy
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: researchfi-api-build
  spec:
    source:
      git:
        uri: https://github.com/sarkikos/research-fi-api.git
        ref: devel
      contextDir: django
    strategy:
      sourceStrategy:
        from:
          kind: DockerImage
          name: centos/python-36-centos7
        env:
          - name: ENABLE_PIPENV
            value: "true"
          - name: APP_HOME
            value: "webapps"
          - name: APP_MODULE
            value: "webapps.wsgi:application"
          - name: DISABLE_SETUP_PY_PROCESSING
            value: "true"
          - name: DISABLE_COLLECTSTATIC
            value: "true"
          - name: DISABLE_MIGRATE
            value: "true"
    output:
      to:
        kind: ImageStreamTag
        name: researchfi-api-test-image:latest
        #kind: DockerImage
        #name: ${ARTIFACTORY}/researchfi-api-rahti/test:latest
    successfulBuildsHistoryLimit: 4 
    failedBuildsHistoryLimit: 4

# BuildConfig using Docker build strategy
#- apiVersion: v1
#  kind: BuildConfig
#  metadata:
#    name: researchfi-api-build
#  spec:
#    source:
#      git:
#        uri: https://github.com/CSCfi/research-fi-api.git
#        ref: devel
#      contextDir: django
#    strategy:
#      dockerStrategy:
#        dockerfilePath: Dockerfile
#    output:
#      to:
#        kind: ImageStreamTag
#        name: researchfi-api:latest
#    successfulBuildsHistoryLimit: 4
#    failedBuildsHistoryLimit: 4

# Jenkins pipeline
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: researchfi-api-pipeline
  spec:
    source:
      git:
        uri: https://github.com/sarkikos/research-fi-api.git
        ref: devel
      contextDir: django
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: openshift/Jenkinsfile

# Deployment config
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: researchfi-api-deployment
  spec:
    template:
      metadata:
        labels:
          name: researchfi-api-deployment
      spec:
        containers:
          - name: researchfi-api-container
            #image: ${ARTIFACTORY}/researchfi-api-rahti/test:latest
            #image: docker-registry.default.svc:5000/ts/researchfi-api-test-image:latest
            imagePullPolicy: Always
            ports:
              - containerPort: 8000
                protocol: TCP
            env:
              - name: DJANGO_ENV_SECRET_KEY
                value: ${DJANGO_ENV_SECRET_KEY}
              - name: DJANGO_ENV_ELASTICSEARCH_HOST
                value: ${DJANGO_ENV_ELASTICSEARCH_HOST}
    replicas: 1
    selector:
      name: researchfi-api-deployment
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - researchfi-api-test
        from:
          kind: ImageStreamTag
          name: researchfi-api-test-image:latest
    strategy:
      type: Rolling

# Job for unit test
#- apiVersion: batch/v1
#  kind: Job
#  metadata:
#    name: researchfi-api
#  spec:
#    template:
#      spec:
#        containers:
#        - name: researchfi-api-test
#          image: ts/researchfi-api
#          command:
#          - sh
#          - -c
#          - cd webapps; python manage.py test;
#          restartPolicy: Never

# Template parameters
parameters:
- name: DJANGO_ENV_SECRET_KEY
  description: Sets Django SECRET_KEY
- name: DJANGO_ENV_ELASTICSEARCH_HOST
  description: Elasticsearch address
#- name: ARTIFACTORY
#  description: Artifactory address, without 'http://' or 'https://', without trailing '/', for example 'myhostname.mydomain.fi'.